require 'nw_plugin_slack_notifier/nw_loader/nw_plugins/initial_load'
require 'nw_plugin_slack_notifier/nw_app_structure/nw_patches/apply/after_one'
require 'nw_plugin_slack_notifier/nw_app_structure/nw_patches/apply/after_two'
require 'nw_plugin_slack_notifier/nw_app_structure/nw_patches/apply/around_one'
require 'nw_plugin_slack_notifier/nw_app_structure/nw_patches/apply/before_one'
require 'nw_plugin_slack_notifier/nw_app_structure/nw_patches/apply/before_two'
